# The URL the site will be built for
base_url = "https://azzamsa.github.io/gntrwiki"
title = "gntrwiki"
description = "Wiki mini untuk ummat"

theme = "adidoks"
default_language = "en"
compile_sass = true
generate_feed = true
minify_html = false

taxonomies = [
  {name = "authors"}, # Basic definition: no feed or pagination
]

build_search_index = true

[search]
include_title = true
include_description = false
include_content = true

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
# Put all your custom variables here
author = "Azzam S.A"
github = "https://github.com/azzamsa"
twitter = "https://twitter.com/azzamsyawqi"

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = "gntrwiki"

# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "Asia/Jakarta"

# Edit page on reposity or not
edit_page = true
docs_repo = "https://github.com/azzamsa/gntrwiki"
repo_branch = "master"

## Open Graph + Twitter Cards
[extra.open]
enable = true
image = "masjid.png"
twitter_site = "azzamsyawqi"
twitter_creator = "azzamsyawqi"
og_locale = "en_US"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "masjid.png"
twitter = "https://twitter.com/azzamsyawqi"
linked_in = ""
github = "https://github.com/azzamsa"
section = "wiki" # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = false


# Menu items
[[extra.menu.main]]
name = "Wiki"
section = "wiki"
url = "/wiki/tentang/sejarah"
weight = 10
